export const defaultValues = {
    name: '',
    announced: '',
    description: '',
    price: '',
    image: '',
    quantity: '',
    cpu: '',
    gpu: '',
    displaySize: '',
    battery: '',
    ram: '',
    storage: '',
    operating_system: '',
    category: '',
}